# Generated by Django 4.1.7 on 2023-02-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodforall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
